name: API Deployment

on:
  push:
    branches:
      - feat/DevOps  # Déclencher le workflow sur les mises à jour de la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.0.0

      - name: Install dependencies
        run: npm install

      - name: Deploy API
        run: |
        # Ajoutez ici les commandes pour déployer votre API sur votre serveur d'hébergement
